import { PERMISSIONS } from "./rolePermissions";

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),

  ADMIN: [
    PERMISSIONS.ADD_USER,
    PERMISSIONS.VIEW_USER,
    PERMISSIONS.EDIT_USER,
    PERMISSIONS.DELETE_USER,

    PERMISSIONS.ENQUIRE_LIST,
    PERMISSIONS.ADD_ENQUIRE,
    PERMISSIONS.EDIT_ENQUIRE,
    PERMISSIONS.DELETE_ENQUIRE,

    PERMISSIONS.VIEW_COURSES,
    PERMISSIONS.ADD_COURSE,
    PERMISSIONS.EDIT_COURSE,

    PERMISSIONS.VIEW_BLOGS,
    PERMISSIONS.VIEW_VIDEOS,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,

    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_REPORTS,

    PERMISSIONS.VIEW_SETTINGS,
  ],

  TECHNICAL_HEAD: [
    PERMISSIONS.VIEW_COURSES,
    PERMISSIONS.ADD_COURSE,
    PERMISSIONS.EDIT_COURSE,
    PERMISSIONS.DELETE_COURSE,

    PERMISSIONS.VIEW_BLOGS,
    PERMISSIONS.ADD_BLOG,
    PERMISSIONS.EDIT_BLOG,
    PERMISSIONS.DELETE_BLOG,

    PERMISSIONS.VIEW_VIDEOS,
    PERMISSIONS.ADD_VIDEO,
    PERMISSIONS.EDIT_VIDEO,
    PERMISSIONS.DELETE_VIDEO,

    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.ADD_ANNOUNCEMENT,
    PERMISSIONS.EDIT_ANNOUNCEMENT,
    PERMISSIONS.DELETE_ANNOUNCEMENT,

    PERMISSIONS.MANAGE_CMS,
    PERMISSIONS.MANAGE_BANNERS,
    PERMISSIONS.MANAGE_PAGES,

    PERMISSIONS.VIEW_ACADEMIC,
    PERMISSIONS.MANAGE_ACADEMIC,

    PERMISSIONS.VIEW_SOCIAL,
    PERMISSIONS.MANAGE_SOCIAL,

    PERMISSIONS.VIEW_REPORTS,
  ],

  HR: [
    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.MANAGE_EMPLOYEES,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.MANAGE_ATTENDANCE,

    PERMISSIONS.VIEW_USER,
    PERMISSIONS.ADD_USER,

    PERMISSIONS.ENQUIRE_LIST,
    PERMISSIONS.ADD_ENQUIRE,

    PERMISSIONS.VIEW_REPORTS,
  ],

  FACULTY: [
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.MANAGE_CLASSES,

    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.MANAGE_ASSIGNMENTS,

    PERMISSIONS.VIEW_ACADEMIC,

    PERMISSIONS.VIEW_COURSES,
    PERMISSIONS.VIEW_BLOGS,
    PERMISSIONS.VIEW_VIDEOS,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
  ],

  STUDENT: [
    PERMISSIONS.VIEW_ENROLLED_COURSES,
    PERMISSIONS.SUBMIT_ASSIGNMENTS,
    PERMISSIONS.VIEW_RESULTS,

    PERMISSIONS.VIEW_ASSIGNMENTS,

    PERMISSIONS.VIEW_COURSES,
    PERMISSIONS.VIEW_BLOGS,
    PERMISSIONS.VIEW_VIDEOS,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
  ],
};
