export const PERMISSIONS = {
    // User Management
    ADD_USER: "ADD_USER",
    VIEW_USER: "VIEW_USER",
    EDIT_USER: "EDIT_USER",
    DELETE_USER: "DELETE_USER",
  
    // Enquiry
    ENQUIRE_LIST: "ENQUIRE_LIST",
    ADD_ENQUIRE: "ADD_ENQUIRE",
    EDIT_ENQUIRE: "EDIT_ENQUIRE",
    DELETE_ENQUIRE: "DELETE_ENQUIRE",
  
    // Course
    VIEW_COURSES: "VIEW_COURSES",
    ADD_COURSE: "ADD_COURSE",
    EDIT_COURSE: "EDIT_COURSE",
    DELETE_COURSE: "DELETE_COURSE",
  
    // Blogs
    VIEW_BLOGS: "VIEW_BLOGS",
    ADD_BLOG: "ADD_BLOG",
    EDIT_BLOG: "EDIT_BLOG",
    DELETE_BLOG: "DELETE_BLOG",
  
    // Videos
    VIEW_VIDEOS: "VIEW_VIDEOS",
    ADD_VIDEO: "ADD_VIDEO",
    EDIT_VIDEO: "EDIT_VIDEO",
    DELETE_VIDEO: "DELETE_VIDEO",
  
    // Announcements
    VIEW_ANNOUNCEMENTS: "VIEW_ANNOUNCEMENTS",
    ADD_ANNOUNCEMENT: "ADD_ANNOUNCEMENT",
    EDIT_ANNOUNCEMENT: "EDIT_ANNOUNCEMENT",
    DELETE_ANNOUNCEMENT: "DELETE_ANNOUNCEMENT",
  
    // CMS
    MANAGE_CMS: "MANAGE_CMS",
    MANAGE_BANNERS: "MANAGE_BANNERS",
    MANAGE_PAGES: "MANAGE_PAGES",
  
    // Academic
    VIEW_ACADEMIC: "VIEW_ACADEMIC",
    MANAGE_ACADEMIC: "MANAGE_ACADEMIC",
  
    // HR
    VIEW_EMPLOYEES: "VIEW_EMPLOYEES",
    MANAGE_EMPLOYEES: "MANAGE_EMPLOYEES",
    VIEW_ATTENDANCE: "VIEW_ATTENDANCE",
    MANAGE_ATTENDANCE: "MANAGE_ATTENDANCE",
  
    // Faculty
    VIEW_CLASSES: "VIEW_CLASSES",
    MANAGE_CLASSES: "MANAGE_CLASSES",
    VIEW_ASSIGNMENTS: "VIEW_ASSIGNMENTS",
    MANAGE_ASSIGNMENTS: "MANAGE_ASSIGNMENTS",
  
    // Student
    VIEW_ENROLLED_COURSES: "VIEW_ENROLLED_COURSES",
    SUBMIT_ASSIGNMENTS: "SUBMIT_ASSIGNMENTS",
    VIEW_RESULTS: "VIEW_RESULTS",
  
    // Reports
    VIEW_REPORTS: "VIEW_REPORTS",
    GENERATE_REPORTS: "GENERATE_REPORTS",
  
    // Settings
    VIEW_SETTINGS: "VIEW_SETTINGS",
    MANAGE_SETTINGS: "MANAGE_SETTINGS",
  
    // System
    SYSTEM_ADMIN: "SYSTEM_ADMIN",
  };
  